#!/bin/bash

input="5 5 5 5"
pass=0
fail=0
if [ "$#" -gt 0 ]; then
    input=$1
fi

cd restricted_testcases || exit
printf "Checking for correct outputs\n"

for file in *.cl; do
    printf "Running test: %s -- " "$file"
    cool --tac "$file"
    them=$(echo "$input" | cool "$file-tac")

    cool --type "$file"
    dune exec --profile=release cool "$file-type" 2> /dev/null
    us=$(echo "$input" | cool "$file-tac")

    if [ "$them" != "$us" ]; then
        echo "FAILED"
        fail=$((fail+1))
    else 
        echo "PASSED"
        pass=$((pass+1))
    fi
    rm "$file-tac"

done
echo "Passed: $pass"
echo "Failed: $fail"

if [ $fail != 0 ]; then 
    exit 1
fi

printf "\nTesting for successful dead code elimination"

fast=0
slow=0
for file in *.cl; do
    printf "Running test: %s -- " "$file"
    cool --tac --opt "$file"
    them=$(cool --profile ref_optimized.cl-tac | grep STEPS)
    them=$(echo "$them" | grep -oE '[0-9]+')


    cool --type "$file"
    dune exec --profile=release cool "$file-type" 2> /dev/null
    us=$(cool --profile my_optimized.cl-tac | grep STEPS)
    us=$(echo "$us" | grep -oE '[0-9]+')

    df=$($them - $us)
    if [ "$them" -gt "$us" ]; then
        fast=$((fast+1))
    else 
        echo "SLOWER"
        slow=$((slow+1))
    fi
    rm ./*.cl-t*
done
echo "Faster: $fast"
echo "Slower: $slow"

cd ..
