#!/bin/bash
input="5 5 5 5"

# if $1.input exists
if [ -f "$1.input" ]; then
    input=$(cat "$1.input")
fi

cool --x86 "$1.cl"
./run-compile "$1.s" 2> /dev/null
cool_output=$(cat "test_input" | ./a.out)

rm a.out

dune_output=$(cat "test_input" | ./run-full "$1")

if [ "$?" -ne 0 ]; then
    echo "Test failed: $1"
    echo "Dune output: "
    echo $dune_output
    exit 1
fi

echo "Expected: $cool_output"
echo "Got:      $dune_output"

if [[ "$cool_output" == ERROR* ]]; then
    cool_output=${cool_output:0:12}
    dune_output=${dune_output:0:12}
fi

if [ "$cool_output" != "$dune_output" ]; then
    # If starts with "ERROR" then only check first 12 characters

    echo "Test failed: $1"
    exit 1
fi

rm "$1".cl-type
rm "$1".s

echo "Test passed: $1"